### PR TITLE
Include module in ApplicationRecord when Spring reloads

### LINKED ISSUE #1: Railtie initialization doesn't happen when Spring reloads
How to reproduce:

* In an application using `acts_as_having_string_id` with working tests, run the tests
* Note that they're not failing
* Touch a file to make spring reload, something like `touch app/models/application_record.rb`
* Re-run the tests

What happens:

The tests fail with an error like

    Error:
    SomethingTest#test_something:
    NameError: undefined local variable or method `acts_as_having_string_id' for #<Class:0x007fd80cff3980>
    app/models/something.rb:2:in `<class:Something>'
    app/models/something.rb:1:in `<top (required)>'`

What I expect to happen:

The tests should work.

A workaround is to `include ActsAsHavingStringId` in your `ApplicationRecord`.

### PR DESCRIPTION
**Pull request by hult**
Fixes #1

### CODE REVIEW

**Comment by leogiertz** [comment]
Works for me!

**Comment by hult** [comment]
Then go ahead and merge!

**Comment by hult** [comment]
No, sorry, go ahead and merge the other one

**Comment by leogiertz** [comment]
You sure? Don't we want to merge this module first so that we can update the other PR to not refer to a local copy?

**Pull request merged**
